<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MuLang.StandardLibrary\MuLang.StandardLibrary.csproj" />
    <ProjectReference Include="..\MuLang.TestSupport\MuLang.TestSupport.csproj" />
  </ItemGroup>

</Project>
